INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (null, 'ENG', 'ING', 65, 0)
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (null, 'EUR', 'ING', 75, 0)
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (null, 'AUD', 'ING', 25, 0)